# Generated by Django 6.0.3 on 2026-04-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.CharField(default='000', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
